show_plots: true

always:
  threshold: 50.0
  interval_steps: [0, 2]
  signal:
    lower: [52.0, 51.0, 53.0, 49.0, 48.0, 54.0, 55.0, 56.0]
    upper: [55.0, 54.0, 56.0, 52.0, 49.0, 57.0, 58.0, 59.0]

eventually:
  threshold: 50.0
  interval_steps: [0, 1]
  signal:
    lower: [45.0, 46.0, 49.0, 47.0, 52.0, 44.0, 43.0]
    upper: [48.0, 49.0, 53.0, 49.0, 55.0, 48.0, 47.0]

nested:
  threshold: 50.0
  always_interval_steps: [0, 1]
  eventually_interval_steps: [0, 1]
  signal:
    lower: [45.0, 52.0, 53.0, 46.0, 49.0, 54.0]
    upper: [48.0, 55.0, 56.0, 49.0, 53.0, 57.0]
