show_plots: true

always:
  signal: &continuous_signal
    type: linear
    control: sinusoidal
    parameters:
      a: 0.01
      b: 1.0
      g: 2.0
      q: 2.5
      mu: 50.0
      P: 0.15
      t_end: 10.0
      n_steps: 100
  sigma_multiplier: 1.0
  threshold: 50.0
  formula:
    operator: always
    interval_sec: [1.0, 2.0]

eventually:
  signal: *continuous_signal
  sigma_multiplier: 1.0
  threshold: 55.0
  formula:
    operator: eventually
    interval_sec: [0.0, 1.0]

nested:
  signal:
    type: piecewise
    values:
      - [45.0, 4.0]
      - [55.0, 4.0]
      - [60.0, 4.0]
      - [48.0, 4.0]
      - [42.0, 9.0]
      - [58.0, 4.0]
      - [52.0, 4.0]
  sigma_multiplier: 1.0
  threshold: 50.0
  formula:
    operator: eventually
    interval_steps: [0, 1]
    child:
      operator: always
      interval_steps: [0, 1]
